# Numpy Tutorial start

In [1]:
import numpy as np

In [2]:
# np.array(parameter) --> parameter can be a list/tuple in python
# np.array(parameter) --> next parameter can be a datatype to store
myarr = np.array([3,66, 78, 99], np.int32)

In [3]:
myarr

array([ 3, 66, 78, 99])

In [4]:
myarr2 = np.array([[1,2,3,4]])

In [5]:
myarr2[0]

array([1, 2, 3, 4])

In [6]:
myarr2[0,3]

4

In [7]:
# returns (rows, columns)
myarr2.shape

(1, 4)

In [8]:
myarr2.dtype

dtype('int32')

In [9]:
# Change elements in array by index
myarr2[0,1] = 99

In [10]:
myarr2

array([[ 1, 99,  3,  4]])

# Types of array creation methods using numpy
# 1. Conversion from other python stuctures passing list/tuples
# 2. intrinsic array creation objects
# 3. Reading from disks
# 4. Creating from raw bytes usinf strings or buffer
# 5. Using special library functions like random() 

# 1. Conversion from other python stuctures passing list/tuples

In [11]:
list = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]

In [12]:
listarray = np.array(list)

In [13]:
listarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
listarray.shape

(3, 4)

In [15]:
listarray.size

12

In [16]:
np.array({1,2,344,56})

array({344, 1, 2, 56}, dtype=object)

# 2. intrinsic array creation objects

In [17]:
# 1 eg
zeros = np.zeros((2,5))

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
zeros.shape

(2, 5)

In [20]:
zeros.size

10

In [21]:
# 2 eg
rng = np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
# 3 eg
lspace = np.linspace(1,3,10) # return 10 nums in (1 to 3) with equal spacing

In [24]:
lspace

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [25]:
# 4 eg
emp = np.empty((4,6))

In [26]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.24611198e-306, 7.56587585e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.33511018e-306, 6.23057689e-307,
        8.45597329e-307, 8.45559303e-307, 8.06613040e-308],
       [6.89810244e-307, 1.22387550e-307, 2.22522596e-306,
        8.34423917e-308, 1.11261162e-306, 1.78021527e-306]])

In [27]:
# 5
emp_like = np.empty_like(lspace) #parameter a previous structure with same size

In [28]:
emp_like

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [29]:
# 5 eg
ide = np.identity(30)

In [30]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0

In [31]:
ide.shape

(30, 30)

In [32]:
arr = np.arange(99)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr = arr.reshape(3,33) # since 3*33 == 99

In [35]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr.shape

(3, 33)

In [37]:
arr = arr.ravel() # converts it into One-D array

In [38]:
arr.shape

(99,)

# Axis in numpy

In [39]:
# 2D array
x = [[1,2,3], [4,5,6], [7,8,9]]
arr = np.array(x)

In [40]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr.sum(axis = 0) 
#axis=1 --> rows span
#axis=0 --> columns span

array([12, 15, 18])

In [42]:
arr.sum(axis = 1)

array([ 6, 15, 24])

In [43]:
arr.T # Transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [44]:
arr.flat # returns an iterator

In [45]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [46]:
arr.ndim # returns number of dimensions

2

In [47]:
arr.size

9

In [48]:
arr.nbytes # returns total bytes consumed by arraay elements

36

In [49]:
one = np.array([5,7,21,454,9])

In [50]:
one.argmax() # returns idex of max element

3

In [51]:
one.argmin()

0

In [52]:
one.argsort()

array([0, 1, 4, 2, 3], dtype=int64)

In [53]:
x = [[1,2,3], [4,5,6], [7,8,0]]
arr2d = np.array(x)

In [54]:
arr2d.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [55]:
arr2d.argmin()

8

In [56]:
arr2d.argmax()

7

In [57]:
arr2d.argmax(axis=1)

array([2, 2, 1], dtype=int64)

In [58]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [59]:
arr2d.argmax(axis=0)

array([2, 2, 1], dtype=int64)

In [60]:
arr2d.argsort(axis=0)

array([[0, 0, 2],
       [1, 1, 0],
       [2, 2, 1]], dtype=int64)

In [61]:
arr2d.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [62]:
arr2d.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 0])

In [63]:
arr2d.shape

(3, 3)

In [64]:
arr2d.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [0]])

In [65]:
arr2d.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 8, 0])

In [66]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr2 = np.array([[3,4,5],
               [9,1,2],
               [0,1,2]])
arr2

array([[3, 4, 5],
       [9, 1, 2],
       [0, 1, 2]])

In [68]:
arr + arr2

array([[ 4,  6,  8],
       [13,  6,  8],
       [ 7,  9, 11]])

In [69]:
[82, 89] + [8, 5] # list is just extended

[82, 89, 8, 5]

In [70]:
arr2/arr

array([[3.        , 2.        , 1.66666667],
       [2.25      , 0.2       , 0.33333333],
       [0.        , 0.125     , 0.22222222]])

In [71]:
np.sqrt(arr2)

array([[1.73205081, 2.        , 2.23606798],
       [3.        , 1.        , 1.41421356],
       [0.        , 1.        , 1.41421356]])

In [72]:
arr.sum()

45

In [73]:
arr.max()

9

In [74]:
arr.min()

1

In [75]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
np.where(arr>5) # returns tuple of array
# Eg here (1,2), (2,0), (2,1), (2,2)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [77]:
type(np.where(arr>5))

tuple

In [78]:
np.count_nonzero(arr)

9

In [79]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [80]:
import sys

In [81]:
py_arr = [1,4,55,2]

In [82]:
np_arr = np.array(py_arr)

In [83]:
sys.getsizeof(1) * len(py_arr)

112

In [84]:
np_arr.itemsize * np_arr.size

16